version: "3.9"

services:
  db:
    image: postgres:13-buster
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test