spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:pool:postgresql://${DB_HOST}:${DB_PORT}/test_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: INFO
    net:
      chrissearle: DEBUG
